import { execFile } from 'node:child_process';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { ClassMeta, ProjectFile } from '../../runtime-contract/src/index.js';

const browserPackage = 'de.tomkarp.bluek.bridge';

const kotlinIdentifier = (value: string) => value.replace(/[^A-Za-z0-9_]/g, '_');
const typeName = (displayName: string) => displayName.trim().replace(/\?$/, '').replace(/<.*$/, '').replace(/^in\s+|^out\s+/, '').trim();
const packageOf = (source: string) => source.match(/^\s*package\s+([A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)/m)?.[1] || '';
const kotlinType = (displayName: string) => {
    const type = typeName(displayName);
    if (type === 'String') return 'String';
    if (type === 'Int') return 'Int';
    if (type === 'Double') return 'Double';
    if (type === 'Float') return 'Float';
    if (type === 'Boolean') return 'Boolean';
    if (type === 'Long') return 'Long';
    if (type === 'Short') return 'Short';
    if (type === 'Byte') return 'Byte';
    return type;
};
const bridgeMethodKey = (method: { name: string; parameters: { type: { displayName: string } }[] }) => `${kotlinIdentifier(method.name)}_${method.parameters.map(parameter => kotlinIdentifier(typeName(parameter.type.displayName))).join('_') || 'noargs'}`;

function bridgeSource(files: ProjectFile[], classes: ClassMeta[]): { source: string; packageName: string } {
    const mainFile = files.find(file => file.fileName === 'Main.kt') || files.find(file => /\bfun\s+main\s*\(/.test(file.source));
    const mainPackage = mainFile ? packageOf(mainFile.source) : '';
    const imports = new Set<string>();
    for (const file of files) {
        const pkg = packageOf(file.source);
        if (pkg && pkg !== mainPackage) for (const klass of classes) if (klass.name && file.source.includes(`class ${klass.name}`)) imports.add(`${pkg}.${klass.name}`);
    }
    const bridgePackage = mainPackage;
    const lines = [
        ...(bridgePackage ? [`package ${bridgePackage}`] : []),
        'import kotlin.js.ExperimentalJsExport',
        'import kotlin.js.JsExport',
        ...[...imports].map(value => `import ${value}`),
        '',
        '@OptIn(ExperimentalJsExport::class)',
        '@JsExport',
        'fun bluekRuntimeVersion(): String = "bluek-js-1"',
        '',
        '@OptIn(ExperimentalJsExport::class)',
        '@JsExport',
        'fun bluekStage(): String = bluekStageJson()',
    ];
    if (mainPackage) lines.push(`import ${mainPackage}.main`);
    if (mainFile) {
        lines.push('', '@OptIn(ExperimentalJsExport::class)', '@JsExport', 'fun bluekStart() { main() }');
    }
    for (const klass of classes.filter(value => value.kind === 'class' && value.constructors.length)) {
        const className = kotlinIdentifier(klass.name);
        const constructor = klass.constructors[0];
        const parameters = (constructor.parameters || []).filter(parameter => !parameter.hasDefault).map((parameter, index) => `arg${index}: ${kotlinType(parameter.type.displayName)}`);
        if ((constructor.parameters || []).some(parameter => parameter.hasDefault)) continue;
        lines.push('', '@OptIn(ExperimentalJsExport::class)', '@JsExport', `fun bluekCreate_${className}(${parameters.join(', ')}): ${klass.name} = ${klass.name}(${parameters.map((_, index) => `arg${index}`).join(', ')})`);
        for (const method of klass.methods.filter(value => value.visibility === 'public' && !('autoGenerated' in value) && !value.typeParameters?.length && !value.returnType.displayName.startsWith('List') && !value.parameters.some(parameter => parameter.type.displayName.startsWith('List')))) {
            const methodName = kotlinIdentifier(method.name);
            const args = (method.parameters || []).filter(parameter => !parameter.hasDefault).map((parameter, index) => `arg${index}: ${kotlinType(parameter.type.displayName)}`);
            if ((method.parameters || []).some(parameter => parameter.hasDefault)) continue;
            const returnType = kotlinType(method.returnType.displayName);
            lines.push('', '@OptIn(ExperimentalJsExport::class)', '@JsExport', `fun bluekInvoke_${className}_${bridgeMethodKey(method)}(receiver: ${klass.name}${args.length ? `, ${args.join(', ')}` : ''}): ${returnType} = receiver.${method.name}(${args.map((_, index) => `arg${index}`).join(', ')})`);
        }
    }
    return { source: `${lines.join('\n')}\n`, packageName: bridgePackage };
}

const run = (command: string, args: string[], cwd: string) => new Promise<{ code: number; out: string; err: string }>(resolve => execFile(command, args, { cwd, maxBuffer: 20e6, timeout: 120000 }, (error, stdout, stderr) => resolve({ code: error ? Number(error.code) || 1 : 0, out: stdout, err: stderr })));

export async function compileBrowserProject(root: string, sessionDir: string, files: ProjectFile[], classes: ClassMeta[]): Promise<{ ok: boolean; diagnostics: string; directory: string }> {
    const buildDir = path.join(sessionDir, 'browser');
    const bridgeDir = path.join(buildDir, 'bridge');
    // Keep Gradle's build directory between generations. Kotlin/JS compilation is
    // expensive; the generated bridge and filtered project are the only inputs
    // that must be replaced for a session compile.
    await fs.rm(path.join(buildDir, 'bridge'), { recursive: true, force: true });
    await fs.rm(path.join(buildDir, 'project'), { recursive: true, force: true });
    await fs.cp(path.join(root, 'browser-runtime'), buildDir, { recursive: true });
    await fs.mkdir(bridgeDir, { recursive: true });
    const browserProjectDir = path.join(buildDir, 'project');
    await fs.mkdir(browserProjectDir, { recursive: true });
    const frameworkFiles = new Set(['Actor.kt', 'World.kt', 'Image.kt', 'BluePlayFunctions.kt']);
    for (const file of files) if (!frameworkFiles.has(file.fileName)) await fs.copyFile(path.join(sessionDir, 'project', file.fileName), path.join(browserProjectDir, file.fileName));
    const bridge = bridgeSource(files, classes);
    await fs.writeFile(path.join(bridgeDir, 'BlueKBridge.kt'), bridge.source);
    const result = await run(path.join(root, 'jvm', 'gradlew'), ['jsBrowserProductionLibraryDistribution', '--no-daemon', `-PbluekProjectDir=${browserProjectDir}`, `-PbluekBridgeDir=${bridgeDir}`], buildDir);
    if (result.code) return { ok: false, diagnostics: `${result.out}\n${result.err}`.trim(), directory: buildDir };
    const output = path.join(buildDir, 'build', 'dist', 'js', 'productionLibrary');
    await fs.cp(output, path.join(buildDir, 'dist'), { recursive: true });
    return { ok: true, diagnostics: '', directory: buildDir };
}
