import express from 'express'; import {execFile,spawn,ChildProcess} from 'node:child_process'; import {promises as fs} from 'node:fs'; import path from 'node:path'; import os from 'node:os'; import {randomUUID} from 'node:crypto'; import {fileURLToPath} from 'node:url'; import type {ProjectFile,ClassMeta,TypeRef} from '../../runtime-contract/src/index.js';
const root=process.cwd(); const app=express(); app.use(express.json({limit:'4mb'})); type Pending={resolve:(value:any)=>void;reject:(error:Error)=>void;timer:NodeJS.Timeout}; type S={dir:string;worker:ChildProcess;generation?:string;files:ProjectFile[];buffer:string;pending:Map<string,Pending>}; const sessions=new Map<string,S>();
const exec=(cmd:string,args:string[],cwd:string)=>new Promise<{code:number;out:string;err:string}>(r=>execFile(cmd,args,{cwd,maxBuffer:20e6},(e,out,err)=>r({code:e?.code?Number(e.code)||1:0,out,err})));
const tr=(s:string):TypeRef=>({classifier:s.trim().replace(/[?<>].*$/,''),arguments:[],nullable:s.trim().endsWith('?'),displayName:s.trim()});
function meta(files:ProjectFile[]):ClassMeta[]{const result:any[]=[];for(const f of files){if(f.kind!=='class')continue;const m=f.source.match(/\b(class|interface|abstract\s+class)\s+(\w+)(?:\s*<([^>]+)>)?\s*(?::\s*([^\{]+))?/);if(!m)continue;const n=m[2];const ps=(s:string)=>s.split(',').map(x=>x.trim()).filter(Boolean).map((x,i)=>{const q=x.match(/(?:val|var)?\s*(\w+)\s*:\s*([^=]+)/);return{name:q?.[1]||`arg${i}`,type:tr(q?.[2]||'Any'),hasDefault:x.includes('=')}});const c=f.source.match(new RegExp('\\b'+n+'\\s*\\(([^)]*)\\)'));const methods:any[]=[];for(const x of f.source.matchAll(/\b(public\s+|private\s+|protected\s+)?(?:override\s+)?fun\s+(\w+)\s*\(([^)]*)\)\s*(?::\s*([^\{=]+))?/g)){if((x[1]||'').trim()==='private')continue;methods.push({id:`${n}::${x[2]}`,name:x[2],declaringType:n,parameters:ps(x[3]),returnType:tr(x[4]||'Unit'),visibility:'public'})}result.push({id:n,name:n,kind:m[1].includes('interface')?'interface':'class',constructors:m[1].includes('interface')?[]:[{id:`${n}::ctor`,parameters:ps(c?.[1]||'')}],methods,properties:[],supertypes:(m[4]||'').split(',').filter(Boolean).map(tr),typeParameters:(m[3]||'').split(',').map(x=>x.trim()).filter(Boolean)})}return result}
function attachWorker(s:S){const fail=(error:Error)=>{for(const pending of s.pending.values()){clearTimeout(pending.timer);pending.reject(error)}s.pending.clear()};s.worker.stdout?.on('data',(chunk:Buffer)=>{s.buffer+=chunk.toString();while(true){const i=s.buffer.indexOf('\n');if(i<0)break;const line=s.buffer.slice(0,i);s.buffer=s.buffer.slice(i+1);try{const value=JSON.parse(line);const requestId=value.requestId;if(!requestId)continue;const pending=s.pending.get(requestId);if(!pending)continue;s.pending.delete(requestId);clearTimeout(pending.timer);pending.resolve(value)}catch{continue}}});s.worker.once('error',()=>fail(Error('worker process failed')));s.worker.once('exit',(_,signal)=>fail(Error(`worker exited${signal?` (${signal})`:''}`)))}
async function ask(s:S,msg:any){return new Promise<any>((resolve,reject)=>{const requestId=randomUUID();const timer=setTimeout(()=>{s.pending.delete(requestId);reject(Error('worker timeout'))},120000);s.pending.set(requestId,{resolve,reject,timer});try{s.worker.stdin?.write(JSON.stringify({...msg,requestId})+'\n')}catch(error){clearTimeout(timer);s.pending.delete(requestId);reject(error)}})}
app.get('/api/examples',async(_,r)=>r.json(await Promise.all((await fs.readdir(path.join(root,'examples'))).map(async n=>({id:n,fileName:n,kind:n==='Helpers.kt'?'functions':'class',source:await fs.readFile(path.join(root,'examples',n),'utf8'),revision:1})))));
app.post('/api/session',async(_,r)=>{const d=await fs.mkdtemp(path.join(os.tmpdir(),'bluek-'));const w=spawn('java',['-jar',path.join(root,'jvm','worker.jar')],{cwd:d});const id=randomUUID();const session={dir:d,worker:w,files:[],buffer:'',pending:new Map<string,Pending>()};sessions.set(id,session);attachWorker(session);r.json({sessionId:id})});
app.post('/api/session/:id/compile',async(req,r)=>{const s=sessions.get(req.params.id);if(!s)return r.sendStatus(404);s.generation=undefined;s.files=[];await fs.mkdir(path.join(s.dir,'project'),{recursive:true});for(const f of req.body.files as ProjectFile[])await fs.writeFile(path.join(s.dir,'project',f.fileName),f.source);const files=req.body.files as ProjectFile[];const z=await exec('kotlinc',files.map(f=>path.join('project',f.fileName)).concat(['-d','project/classes']),s.dir);const gid=randomUUID();if(!z.code){s.files=files;s.generation=gid;await ask(s,{op:'load',path:path.join(s.dir,'project/classes')})}r.json({generationId:gid,sourceRevision:req.body.revision||1,classes:meta(files),diagnostics:z.code?[{fileName:'project',line:1,column:1,message:z.err||z.out,severity:'error'}]:[]})});
app.post('/api/session/:id/input',async(req,r)=>{const s=sessions.get(req.params.id);if(!s?.generation)return r.status(409).json({message:'Compile the project first'});if(!s.worker.stdin?.writable)return r.status(503).json({message:'Worker is not available'});s.worker.stdin.write(JSON.stringify({op:'input',text:String(req.body.text??'')})+'\n');r.sendStatus(202)});
app.post('/api/session/:id/action',async(req,r)=>{const s=sessions.get(req.params.id);if(!s?.generation)return r.status(409).json({message:'Compile the project first'});try{r.json(await ask(s,req.body))}catch(e){r.status(500).json({message:String(e)})}}); app.use(express.static(path.join(root,'frontend/dist')));app.listen(5173,()=>console.log('BlueK: http://localhost:5173'));
