import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
import { HttpRuntimeClient } from './runtimeClient';

type FileModel = { id: string; fileName: string; kind: 'class' | 'functions'; source: string; revision: number };
type ClassModel = { id: string; name: string; kind: string; constructors: any[]; methods: any[]; typeParameters?: string[] };
type ObjectModel = { objectId: string; className: string; name: string };
type ResourceModel = { path: string; data: string };

const typeName = (type: any) => type?.displayName || 'Any';
const kotlinCallArguments = (parameters: any[] = [], values: string[]) => { const firstMissing = values.findIndex(value => !value.trim()); if (firstMissing < 0 || parameters.slice(firstMissing).some((parameter, index) => !values[firstMissing + index].trim() && !parameter.hasDefault)) return values; return values.map((value, index) => value.trim() ? (index > firstMissing ? `${parameters[index].name} = ${value}` : value) : '').filter(Boolean); };
const runtimeClassName = (object: ObjectModel) => object.className.replace(/\s*<.*>$/, '');
const splitTypeArguments = (text: string) => { const values: string[] = []; let start = 0, depth = 0; for (let index = 0; index < text.length; index += 1) { if (text[index] === '<') depth += 1; else if (text[index] === '>') depth -= 1; else if (text[index] === ',' && depth === 0) { values.push(text.slice(start, index).trim()); start = index + 1; } } if (text.slice(start).trim()) values.push(text.slice(start).trim()); return values; };
const specializeCallable = (callable: any, object: ObjectModel, classes: ClassModel[]) => { const classMeta = classes.find(value => value.name === runtimeClassName(object)); const actual = object.className.match(/<(.+)>$/)?.[1]; if (!classMeta || !actual) return callable; const actualArguments = splitTypeArguments(actual); const argumentsByName = new Map((classMeta.typeParameters || []).map((name, index) => [name, actualArguments[index]])); const specialize = (type: any): any => { const replacement = argumentsByName.get(type?.classifier); if (replacement) return { ...type, classifier: replacement.replace(/\?$/, ''), arguments: [], nullable: replacement.endsWith('?'), displayName: replacement }; if (!type) return type; const argumentsList = (type.arguments || []).map(specialize); const projection = type.projection === 'in' || type.projection === 'out' ? `${type.projection} ` : ''; const displayName = `${projection}${type.classifier}${argumentsList.length ? `<${argumentsList.map((argument: any) => argument.displayName).join(', ')}>` : ''}${type.nullable ? '?' : ''}`; return { ...type, arguments: argumentsList, displayName }; }; return { ...callable, parameters: (callable.parameters || []).map((parameter: any) => ({ ...parameter, type: specialize(parameter.type) })), returnType: specialize(callable.returnType) }; };
const signatureParams = (parameters: any[] = []) => parameters.map(parameter => `${parameter.name}: ${typeName(parameter.type)}${parameter.hasDefault ? ' = …' : ''}`).join(', ');
const methodText = (method: any) => `${method.returnType?.displayName && method.returnType.displayName !== 'Unit' ? `${typeName(method.returnType)} ` : ''}${method.name}(${signatureParams(method.parameters)})${method.inheritedFrom ? `  [inherited from ${method.inheritedFrom}]` : ''}`;
const classPopupItems = (classMeta: any) => [...classMeta.constructors.map((constructor: any, index: number) => ({ ...constructor, name: classMeta.name, index, isConstructor: true })), ...(classMeta.companionMethods || []).map((method: any) => ({ ...method, isCompanion: true }))];

function App() {
  const [files, setFiles] = useState<FileModel[]>([]), [classes, setClasses] = useState<ClassModel[]>([]), [sessionId, setSessionId] = useState(''), [generation, setGeneration] = useState(''), [selected, setSelected] = useState(0), [bench, setBench] = useState<ObjectModel[]>([]), [selectedObjectId, setSelectedObjectId] = useState(''), [code, setCode] = useState(''), [log, setLog] = useState(''), [status, setStatus] = useState('Ready');
  const [resources, setResources] = useState<ResourceModel[]>([]);
  const [stage, setStage] = useState<any>(null), [speed, setSpeed] = useState(50);
  const liveOutput = useRef(new Map<string, string>());
  const runtimeFailure = useRef('');
  const [createClass, setCreateClass] = useState<ClassModel | null>(null), [constructorIndex, setConstructorIndex] = useState(0), [genericArgs, setGenericArgs] = useState<string[]>([]), [constructorArgs, setConstructorArgs] = useState<string[]>([]), [menu, setMenu] = useState<{ x: number; y: number; object?: ObjectModel; classMeta?: ClassModel } | null>(null), [method, setMethod] = useState<{ object?: ObjectModel; receiver?: string; meta: any } | null>(null), [methodArgs, setMethodArgs] = useState<string[]>([]), [inspect, setInspect] = useState<any>(null), [editor, setEditor] = useState(false);

  useEffect(() => { Promise.all([fetch('/api/examples').then(response => response.json()), fetch('/api/session', { method: 'POST' }).then(response => response.json())]).then(([initialFiles, session]) => { setFiles(initialFiles); setSessionId(session.sessionId); }); }, []);
  useEffect(() => { if (!sessionId) return; const close = () => { navigator.sendBeacon(`/api/session/${sessionId}/close`, ''); }; window.addEventListener('pagehide', close); return () => window.removeEventListener('pagehide', close); }, [sessionId]);
  const handleRuntimeFailure = (message: string) => { if (runtimeFailure.current === message) return; runtimeFailure.current = message; setGeneration(''); setBench([]); setSelectedObjectId(''); setStage(null); setStatus('Runtime stopped'); setLog(previous => `${previous}\n${message}`); };
  const client = useMemo(() => sessionId ? new HttpRuntimeClient(sessionId, handleRuntimeFailure) : null, [sessionId]);
  useEffect(() => { if (!generation || !client) return; const timer = window.setInterval(() => { client.stage().then(value => { if (!value?.stage) return; runtimeFailure.current = ''; setStage(value.stage); (value.stage.errors || []).forEach((error: string) => setLog(previous => `${previous}\n${error}`)); (value.stage.sounds || []).forEach((sound: string) => { const resource = resources.find(item => item.path === `sounds/${sound}` || item.path.endsWith(`/sounds/${sound}`)); if (resource) new Audio(resource.data).play().catch(() => undefined); }); }).catch(() => undefined); }, 250); return () => window.clearInterval(timer); }, [generation, client, resources]);
  useEffect(() => { if (!generation || !client) return; const timer = window.setInterval(() => { client.events().then(events => events.forEach(writeLive)).catch(() => undefined); }, 150); return () => window.clearInterval(timer); }, [generation, client]);
  const write = (value: any) => { if (value.stage) setStage(value.stage); const alreadyLive = value.requestId ? liveOutput.current.get(value.requestId) || '' : ''; const output = value.output && alreadyLive && value.output.startsWith(alreadyLive) ? value.output.slice(alreadyLive.length) : value.output || ''; if (value.requestId) liveOutput.current.delete(value.requestId); setLog(previous => `${previous}\n${output}${value.display || value.message || ''}`); };
  const writeLive = (value: any) => { const output = value.output || ''; if (!output) return; if (value.requestId) liveOutput.current.set(value.requestId, `${liveOutput.current.get(value.requestId) || ''}${output}`); setLog(previous => `${previous}\n${output}`); };
  const addReturnedObject = (value: any) => { if (!value?.objectId) return; const object = { objectId: value.objectId, className: value.display || 'Object', name: value.name || `object${Date.now()}` }; setBench(previous => previous.some(item => item.objectId === object.objectId) ? previous : [...previous, object]); setSelectedObjectId(object.objectId); };
  const action = async (request: any) => { if (!client) return { kind: 'error', display: 'Runtime is not ready.' }; try { const response = await client.execute({ ...request, generationId: generation }); write(response); return response; } catch (error) { const message = error instanceof Error ? error.message : 'Runtime request failed.'; setLog(previous => `${previous}\n${message}`); return { kind: 'error', display: message }; } };
  const stop = async () => { if (!client) return; try { await client.stop(); setBench([]); setSelectedObjectId(''); setGeneration(''); setStage(null); setStatus('Stopped'); write({ kind: 'reset', display: 'Runtime stopped. Compile again to create new objects.' }); } catch (error) { setLog(previous => `${previous}\n${error instanceof Error ? error.message : 'Runtime stop failed.'}`); } };
  const sendInput = async (event: React.KeyboardEvent<HTMLInputElement>) => { if (event.key !== 'Enter') return; const input = event.currentTarget, text = input.value; input.value = ''; if (!text) return; setLog(previous => `${previous}\n> ${text}`); try { await client?.sendInput(text); } catch (error) { setLog(previous => `${previous}\n${error instanceof Error ? error.message : 'Input failed.'}`); } };
  const sendKey = (event: React.KeyboardEvent<HTMLDivElement>, pressed: boolean) => { const key = ({ ArrowLeft: 'left', ArrowRight: 'right', ArrowUp: 'up', ArrowDown: 'down', ' ': 'space' } as Record<string, string>)[event.key] || event.key.toLowerCase(); client?.sendKey(key, pressed).catch(() => undefined); };
  const sendClick = (event: React.MouseEvent<HTMLDivElement>) => { if (!stage) return; const bounds = event.currentTarget.getBoundingClientRect(); const x = Math.round(((event.clientX - bounds.left) / bounds.width) * Math.max(stage.width - 1, 0)); const y = Math.round(((event.clientY - bounds.top) / bounds.height) * Math.max(stage.height - 1, 0)); client?.sendClick(x, y).catch(() => undefined); };
  const bluePlayAction = (code: string) => { action({ op: 'eval', code, mode: 'expression' }); };
  const changeSpeed = (value: number) => { setSpeed(value); bluePlayAction(`setSpeed(${value})`); };
  const compile = async () => { if (!client) return; setStatus('Compiling…'); try { const result = await client.compile(files, Date.now(), resources); setClasses(result.classes || []); setBench([]); setSelectedObjectId(''); setGeneration(result.diagnostics?.length ? '' : result.generationId); setStage(null); setSpeed(50); setLog(result.diagnostics?.map((diagnostic: any) => `${diagnostic.fileName}: ${diagnostic.message}`).join('\n') || 'Compiled successfully. Object bench cleared.'); setStatus(result.diagnostics?.length ? 'Compile error' : 'Compiled'); } catch (error) { setStatus('Compile error'); setLog(previous => `${previous}\n${error instanceof Error ? error.message : 'Compilation failed.'}`); } };
  const importResources = async (event: React.ChangeEvent<HTMLInputElement>) => { const selectedFiles = Array.from(event.target.files || []); const imported = await Promise.all(selectedFiles.map(file => new Promise<ResourceModel>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve({ path: `${file.type.startsWith('audio/') || /\.wav$/i.test(file.name) ? 'sounds' : 'images'}/${file.name}`, data: String(reader.result) }); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); }))); setResources(previous => [...previous.filter(resource => !imported.some(item => item.path === resource.path)), ...imported]); setStatus('Uncompiled'); event.target.value = ''; };
  const addFile = (kind: 'class' | 'functions') => { const stem = kind === 'class' ? 'NewClass' : 'Functions'; let number = 1, name = `${stem}${number}`; while (files.some(file => file.fileName === `${name}.kt`)) name = `${stem}${++number}`; const source = kind === 'class' ? `class ${name} {\n}\n` : '// Add top-level Kotlin functions here\n'; const file: FileModel = { id: `local-${Date.now()}`, fileName: `${name}.kt`, kind, source, revision: 1 }; setFiles(previous => [...previous, file]); setSelected(files.length); setStatus('Uncompiled'); setEditor(true); };
  const updateSource = (source: string) => { setStatus('Uncompiled'); setFiles(previous => previous.map((file, index) => index === selected ? { ...file, source } : file)); };
  const openCreate = (classMeta: ClassModel, index = 0) => { setCreateClass(classMeta); setConstructorIndex(index); setGenericArgs((classMeta.typeParameters || []).map(() => '')); setConstructorArgs(classMeta.constructors[index]?.parameters?.map(() => '') || []); };
  const chooseConstructor = (index: number) => { if (!createClass) return; setConstructorIndex(index); setConstructorArgs(createClass.constructors[index]?.parameters?.map(() => '') || []); };
  const confirmCreate = () => { if (!createClass) return; const name = `${createClass.name.toLowerCase()}${bench.length + 1}`; const parameters = createClass.constructors[constructorIndex]?.parameters || []; action({ op: 'create', className: createClass.name, name, typeArguments: JSON.stringify(genericArgs.filter(Boolean)), args: JSON.stringify(kotlinCallArguments(parameters, constructorArgs)) }).then(result => { if (result.objectId) { setBench(previous => [...previous, { ...result, className: result.display || createClass.name, name }]); setSelectedObjectId(result.objectId); } }).finally(() => setCreateClass(null)); };
  const invoke = () => { if (!method) return; const args = kotlinCallArguments(method.meta.parameters || [], methodArgs); const request = method.object ? { op: 'invoke', objectId: method.object.objectId, name: method.meta.name, args: JSON.stringify(args) } : { op: 'eval', code: `${method.receiver || ''}${method.meta.name}(${args.join(', ')})`, mode: 'expression' }; action(request).then(addReturnedObject).finally(() => setMethod(null)); };

  return <div className="bluek" onClick={() => setMenu(null)}>
    <div className="menubar"><span>Project</span><span>Edit</span><span>View</span><span>Tools</span><span>Help</span><span className="status">{status}</span></div>
    <div className="body"><nav className="sidebar"><button onClick={() => addFile('class')}>New Class</button><button onClick={() => addFile('functions')}>New Functions</button><label className="resource-button">Add Media<input type="file" accept="image/*,audio/wav,audio/x-wav" multiple onChange={importResources} /></label><button onClick={compile} disabled={!client}>Compile</button><button onClick={compile} disabled={!generation}>Re-run</button><div className="side-spacer" /></nav>
      <section className="workspace"><div className="canvas">{stage && <><div className="game-stage" tabIndex={0} onKeyDown={event => sendKey(event, true)} onKeyUp={event => sendKey(event, false)} onMouseDown={sendClick} style={{ aspectRatio: `${stage.width || 1} / ${stage.height || 1}`, backgroundImage: stage.image || undefined, backgroundSize: '100% 100%' }}>{stage.objects.map((object: any, index: number) => <div className={`game-actor${object.image ? ' image' : ''}`} key={`${object.type}-${index}`} title={object.type} style={{ left: `${((object.x + 0.5) / Math.max(stage.width, 1)) * 100}%`, top: `${((object.y + 0.5) / Math.max(stage.height, 1)) * 100}%`, width: object.imageWidth ? `${(object.imageWidth / (stage.width * stage.cellSize)) * 100}%` : undefined, height: object.imageHeight ? `${(object.imageHeight / (stage.height * stage.cellSize)) * 100}%` : undefined, backgroundImage: object.image || undefined, backgroundSize: '100% 100%', opacity: object.imageOpacity ?? 1, transform: `translate(-50%, -50%) rotate(${object.rotation}deg)` }}>{object.image ? '' : object.type.slice(0, 1)}</div>)}{(stage.texts || []).map((text: any, index: number) => <span className="game-text" key={`${text.x}-${text.y}-${index}`} style={{ left: `${(text.x / Math.max(stage.width - 1, 1)) * 100}%`, top: `${(text.y / Math.max(stage.height - 1, 1)) * 100}%` }}>{text.text}</span>)}</div><div className="game-controls"><button onClick={() => bluePlayAction('step()')}>Act</button><button onClick={() => bluePlayAction('start()')}>Run</button><button onClick={() => bluePlayAction('stop()')}>Pause</button><label>Speed <input type="range" min="1" max="100" value={speed} onChange={event => changeSpeed(Number(event.target.value))} /></label></div></>}<div className="cards">{files.map((file, index) => { const classMeta = classes.find(value => value.name === file.fileName.replace('.kt', '')); return <article className="classcard" key={file.id} onClick={() => setSelected(index)} onDoubleClick={() => { setSelected(index); setEditor(true); }} onContextMenu={event => { event.preventDefault(); if (!classMeta) return; if (file.kind === 'functions' || classMeta.kind === 'object' || (classMeta.kind === 'class' && classMeta.constructors.length > 0)) setMenu({ x: event.clientX, y: event.clientY, classMeta }); }}><small>{file.kind === 'functions' ? '«functions»' : ''}</small><strong>{file.fileName.replace('.kt', '')}</strong></article>; })}</div></div>
        <div className="lower"><section className="bench"><div className="bench-items">{bench.map(object => <div className={`object${selectedObjectId === object.objectId ? ' selected' : ''}`} key={object.objectId} onDoubleClick={() => { setSelectedObjectId(object.objectId); action({ op: 'inspect', objectId: object.objectId }).then(setInspect); }} onContextMenu={event => { event.preventDefault(); event.stopPropagation(); setSelectedObjectId(object.objectId); setMenu({ x: event.clientX, y: event.clientY, object }); }} onClick={event => { event.stopPropagation(); setSelectedObjectId(object.objectId); setMenu(null); }}>{object.name}:<br /><span>{object.className}</span></div>)}</div></section>
          <section className="codepad"><textarea value={code} onChange={event => setCode(event.target.value)} placeholder={'val p = Person("Ada")'} /><div><button onClick={() => action({ op: 'eval', code, mode: 'block' })} disabled={!generation || !code.trim()}>Run</button><button onClick={() => action({ op: 'eval', code, mode: 'expression' }).then(addReturnedObject)} disabled={!generation || !code.trim()}>Evaluate</button><button onClick={stop} disabled={!generation}>Stop</button></div></section></div>
        <footer><span>{bench.find(object => object.objectId === selectedObjectId) ? `${bench.find(object => object.objectId === selectedObjectId)!.name} : ${bench.find(object => object.objectId === selectedObjectId)!.className}` : 'No object selected'}</span><div className="console"><pre>{log}</pre><input placeholder="Console input" onKeyDown={sendInput} disabled={!generation} /></div></footer></section>
    </div>
    {(menu?.object || menu?.classMeta) && <div className="popup" style={{ left: menu.x, top: menu.y }} onClick={event => event.stopPropagation()}><div className="popup-title">{menu.object?.className || menu.classMeta?.name}</div>{(menu.object ? classes.find(value => value.name === runtimeClassName(menu.object!))?.methods : menu.classMeta?.kind === 'class' ? classPopupItems(menu.classMeta) : menu.classMeta?.methods)?.map(meta => <button key={meta.id} onClick={() => { if ((meta as any).isConstructor) { openCreate(menu.classMeta!, (meta as any).index); setMenu(null); return; } const visibleMeta = menu.object ? specializeCallable(meta, menu.object, classes) : meta; const receiver = menu.object ? '' : (menu.classMeta?.kind === 'object' || (meta as any).isCompanion) ? `${menu.classMeta.name}.` : ''; if (!(visibleMeta.parameters || []).length) { const request = menu.object ? { op: 'invoke', objectId: menu.object.objectId, name: visibleMeta.name, args: '[]' } : { op: 'eval', code: `${receiver}${visibleMeta.name}()`, mode: 'expression' }; action(request).then(addReturnedObject); setMenu(null); } else { setMethod({ object: menu.object, receiver, meta: visibleMeta }); setMethodArgs(visibleMeta.parameters.map(() => '')); setMenu(null); } }}>{(meta as any).isConstructor ? `${menu.classMeta!.name}(${signatureParams(meta.parameters)})` : methodText(menu.object ? specializeCallable(meta, menu.object, classes) : meta)}</button>)}{menu.object && <><hr /><button onClick={() => { action({ op: 'inspect', objectId: menu.object!.objectId }).then(setInspect); setMenu(null); }}>Inspect</button><button onClick={() => { const removedId = menu.object!.objectId; action({ op: 'remove', objectId: removedId }).then(result => { if (result.kind !== 'unit') return; setBench(previous => previous.filter(object => object.objectId !== removedId)); if (selectedObjectId === removedId) setSelectedObjectId(''); }); setMenu(null); }}>Remove</button></>}</div>}
    {editor && <div className="modal"><div className="dialog editor-dialog"><h3>{files[selected]?.fileName}</h3><textarea autoFocus value={files[selected]?.source || ''} onChange={event => updateSource(event.target.value)} /><button onClick={() => setEditor(false)}>Close</button></div></div>}
    {createClass && <div className="modal"><div className="dialog"><h3>{createClass.name}{genericArgs.length ? `<${genericArgs.map(value => value || '…').join(', ')}>` : ''}({signatureParams(createClass.constructors[constructorIndex]?.parameters)})</h3>{createClass.constructors.length > 1 && <label>Constructor<select value={constructorIndex} onChange={event => chooseConstructor(Number(event.target.value))}>{createClass.constructors.map((constructor: any, index: number) => <option key={constructor.id} value={index}>{createClass.name}({signatureParams(constructor.parameters)})</option>)}</select></label>}{genericArgs.length > 0 && genericArgs.map((value, index) => <label key={`type-${index}`}>Type argument {index + 1}<input autoFocus={index === 0} value={value} onChange={event => setGenericArgs(previous => previous.map((item, position) => position === index ? event.target.value : item))} placeholder="Kotlin type, e.g. String" /></label>)}{(createClass.constructors[constructorIndex]?.parameters || []).map((parameter: any, index: number) => <label key={parameter.name || index}>{parameter.name}: {typeName(parameter.type)}{parameter.hasDefault ? ' (optional)' : ''}<input autoFocus={index === 0 && genericArgs.length === 0} value={constructorArgs[index] || ''} onChange={event => setConstructorArgs(previous => previous.map((value, position) => position === index ? event.target.value : value))} placeholder="Kotlin expression; strings need quotes" /></label>)}<button onClick={confirmCreate}>Create</button><button onClick={() => setCreateClass(null)}>Cancel</button></div></div>}
    {method && <div className="modal"><div className="dialog"><h3>{methodText(method.meta)}</h3>{(method.meta.parameters || []).map((parameter: any, index: number) => <label key={parameter.name || index}>{parameter.name}: {typeName(parameter.type)}{parameter.hasDefault ? ' (optional)' : ''}<input autoFocus={index === 0} value={methodArgs[index] || ''} onChange={event => setMethodArgs(previous => previous.map((value, position) => position === index ? event.target.value : value))} placeholder="Kotlin expression; strings need quotes" /></label>)}<button onClick={invoke}>Invoke</button><button onClick={() => setMethod(null)}>Cancel</button></div></div>}
    {inspect && <div className="inspector"><div className="inspect-window"><h2>{bench.find(object => object.objectId === selectedObjectId)?.name || 'Object'} Inspector</h2><div className="field">{inspect.display}</div><button onClick={() => setInspect(null)}>Close</button></div></div>}
  </div>;
}

createRoot(document.getElementById('root')!).render(<App />);
