import type {
  CallableMeta,
  ClassMeta,
  ProjectFile,
} from "../../runtime-contract/src/index";
import type { BenchObject } from "./uiTypes";
import { specializeCallable, runtimeClassName } from "./uiParity";

export type MenuCallable = CallableMeta & {
  overrides?: string;
  isCompanion?: boolean;
};

/** Kotlin notation: `give(): Int`; Unit results are omitted. */
export function methodLabel(method: MenuCallable) {
  const returnType =
    method.returnType?.displayName && method.returnType.displayName !== "Unit"
      ? `: ${method.returnType.displayName}`
      : "";
  const typeParameters = method.typeParameters?.length
    ? `<${method.typeParameters.join(", ")}>`
    : "";
  const parameters = (method.parameters || [])
    .map(
      (parameter) =>
        `${parameter.name}: ${parameter.type?.displayName || "Any?"}${parameter.hasDefault ? " = …" : ""}`,
    )
    .join(", ");
  const inherited = method.inheritedFrom
    ? `  [inherited from ${method.inheritedFrom}]`
    : "";
  const generated = method.autoGenerated ? "  [auto-generated]" : "";
  return `${method.name}${typeParameters}(${parameters})${returnType}${inherited}${generated}`;
}
export function popupObjectMethods(object: BenchObject, classes: ClassMeta[]) {
  return (
    (
      classes.find((item) => item.name === runtimeClassName(object))?.methods ||
      []
    )
      // Like BlueJ, private methods are implementation details of the class.
      .filter(
        (method) => !method.autoGenerated && method.visibility !== "private" && method.visibility !== "protected",
      )
      .map((method) => specializeCallable(method, object, classes))
  );
}
export function directPopupMethods(object: BenchObject, classes: ClassMeta[]) {
  const methods = popupObjectMethods(object, classes),
    inheritedNames = new Set(
      methods
        .filter((method) => method.inheritedFrom)
        .map((method) => `${method.name}(${(method.parameters || []).length})`),
    ),
    className = object.className.replace(/\s*<.*>$/, "");
  return methods
    .filter((method) => !method.inheritedFrom)
    .map((method) => ({
      ...method,
      overrides: inheritedNames.has(
        `${method.name}(${(method.parameters || []).length})`,
      )
        ? className
        : undefined,
    }));
}
export function inheritedPopupGroups(
  object: BenchObject,
  classes: ClassMeta[],
) {
  const groups = new Map<string, MenuCallable[]>();
  popupObjectMethods(object, classes)
    .filter((method) => method.inheritedFrom)
    .forEach((method) => {
      const owner = method.inheritedFrom as string;
      groups.set(owner, [...(groups.get(owner) || []), method]);
    });
  const order: string[] = [];
  const visit = (name: string) => {
    const owner = classes.find((item) => item.name === name);
    (owner?.supertypes || [])
      .map((value) =>
        (typeof value === "string"
          ? value
          : value?.classifier || value?.displayName || ""
        ).replace(/\s*<.*>$/, ""),
      )
      .filter(Boolean)
      .forEach((parent: string) => {
        if (!order.includes(parent)) {
          order.push(parent);
          visit(parent);
        }
      });
  };
  visit(object.className.replace(/\s*<.*>$/, ""));
  order.reverse();
  return [...groups.entries()].sort(
    ([left], [right]) =>
      (order.indexOf(left) < 0
        ? Number.MAX_SAFE_INTEGER
        : order.indexOf(left)) -
      (order.indexOf(right) < 0
        ? Number.MAX_SAFE_INTEGER
        : order.indexOf(right)),
  );
}
export function popupObjectMethodLabel(method: MenuCallable) {
  const label = methodLabel({
    ...method,
    inheritedFrom: undefined,
    autoGenerated: false,
  });
  return method.overrides
    ? `${label}  [redefined in ${method.overrides}]`
    : label;
}
export function fileMethods(file: ProjectFile, classes: ClassMeta[]) {
  const owner = classes.find(
    (item) => item.name === file.fileName.replace(/\.kt$/, ""),
  );
  return owner?.kind === "functions" || owner?.kind === "object"
    ? (owner.methods || []).filter((method) => method.visibility !== "private" && method.visibility !== "protected")
    : (owner?.companionMethods || []).map((method) => ({
        ...method,
        isCompanion: true,
      }));
}
