export type FileKind='class'|'functions';
export interface ProjectFile{id:string;path?:string;fileName:string;kind:FileKind;source:string;revision:number}
export interface ProjectLibrary { id: 'blueplay'; version: 1 }
export interface ProjectResource {
  path: string;
  data: string;
  /** Runtime-only decoded image metadata; never persisted in project files. */
  imageWidth?: number;
  imageHeight?: number;
  /** Two hexadecimal alpha digits per source pixel, row-major. */
  alphaHex?: string;
}
export interface ProjectCardPosition { x: number; y: number }
export interface TypeRef{classifier:string;arguments:TypeRef[];nullable:boolean;displayName:string;projection?:'in'|'out'|'star'}
export interface CallableMeta{id:string;name:string;declaringType:string;parameters:{name:string;type:TypeRef;hasDefault:boolean}[];returnType:TypeRef;visibility:string;inheritedFrom?:string;typeParameters?:string[];sourceFile?:string;builtin?:boolean}
export interface CallableMeta { autoGenerated?: boolean; propertyName?: string; companion?: boolean }
export interface ClassMeta{id:string;name:string;qualifiedName?:string;kind:string;constructors:ManifestConstructor[];methods:CallableMeta[];properties:ManifestProperty[];supertypes:TypeRef[];typeParameters:string[]}
export interface ClassMeta { companionMethods?: CallableMeta[] }
export interface ClassMeta { builtin?: boolean; documentation?: string }
export interface ManifestConstructor{ id:string; parameters:{name:string; type:TypeRef; hasDefault:boolean}[] }
export interface ManifestProperty{ id:string; name:string; type:TypeRef; mutable:boolean; visibility:string; getter?:boolean; setter?:boolean; getterId?:string; setterId?:string; generated?:boolean }
export interface ManifestCallable extends CallableMeta{ generated?:boolean; companion?:boolean }
export interface ManifestClass{
    id:string;
    name:string;
    qualifiedName?:string;
    kind:'class'|'abstract'|'interface'|'object'|'enum'|'annotation'|'functions';
    modifiers:string[];
    typeParameters:string[];
    supertypes:TypeRef[];
    constructors:ManifestConstructor[];
    properties:ManifestProperty[];
    methods:ManifestCallable[];
    builtin?: boolean;
}
export interface SymbolManifest{ version:1; classes:ManifestClass[]; functions:(ManifestCallable & {sourceLine:number})[]; library?: ProjectLibrary }
export interface Diagnostic { fileName?:string; line:number; column:number; severity:'error'|'warning'; message:string }
export interface CompileResult{generationId:string;sourceRevision:number;classes:ClassMeta[];diagnostics:Diagnostic[]}
export interface RuntimeEffect { type: 'sound'; name: string }

export interface BluePlayImageFrame {
  resourcePath?: string;
  operations?: string[];
  width: number;
  height: number;
  opacity: number;
}
export interface BluePlayActorFrame {
  objectId?: string;
  /** Stable runtime identity used for pixel-accurate pointer targeting. */
  hitId?: string;
  className: string;
  x: number;
  y: number;
  rotation: number;
  image: BluePlayImageFrame;
  /** Compatibility fields for projects using the pre-library adapter. */
  imagePath?: string;
  imageOperations?: string[];
  imageWidth?: number;
  imageHeight?: number;
  imageOpacity?: number;
}
export interface BluePlayTextFrame { x: number; y: number; text: string }
export interface BluePlayStage {
  worldId?: string;
  frameVersion: number;
  width: number;
  height: number;
  cellSize: number;
  backgroundColor: string;
  backgroundPath?: string;
  backgroundOperations?: string[];
  objects: BluePlayActorFrame[];
  texts: BluePlayTextFrame[];
  speed: number;
  simulation: 'running' | 'paused' | 'stopping';
  sounds?: string[];
}
export type SimulationState = 'inactive' | 'paused' | 'running' | 'stopping' | 'waiting' | 'faulted';

/** A session has exactly one phase, shared by every UI surface. */
export type Phase = 'uncompiled' | 'compiling' | 'ready' | 'running' | 'waitingForInput' | 'faulted';
export interface InspectedField { name: string; value: string; type?: TypeRef | null; setterPrivate?: boolean }
export interface RuntimeValue {
  kind: 'unit' | 'null' | 'scalar' | 'object' | 'inspect' | 'error';
  display?: string;
  diagnostics?: Diagnostic[];
  type?: TypeRef;
  objectId?: string;
  className?: string;
  name?: string;
  fields?: InspectedField[];
  phase?: 'request' | 'analysis' | 'runtime' | 'transport';
  fatal?: boolean;
  output?: string;
  stage?: BluePlayStage;
  effects?: RuntimeEffect[];
}
export interface RuntimeReference {
  name: string;
  objectId: string | null;
  className: string;
  origin: 'interactive' | 'persistent';
  onBench: boolean;
}
export interface RuntimeSnapshot {
  generationId: string;
  revision: number;
  phase: Phase;
  classes: ClassMeta[];
  inspections: Record<string, RuntimeValue>;
  references: RuntimeReference[];
  liveObjectIds: string[];
  error: string | null;
  simulation: SimulationState;
  stage?: BluePlayStage;
}
export type RuntimeCommand = { generationId?: string } & (
  | { op: 'eval'; code: string; filename?: string }
  | { op: 'main'; fileName: string }
  | { op: 'create'; className: string; name: string; args: string[]; typeArguments?: string[] }
  | { op: 'invoke'; objectId: string; name: string; args: string[]; typeArguments?: string[] }
  | { op: 'get'; objectId: string; property: string }
  | { op: 'set'; objectId: string; property: string; value: string }
  | { op: 'inspect'; objectId: string }
  | { op: 'bind'; objectId: string; name: string }
  | { op: 'remove'; objectId: string; name: string }
  | { op: 'input'; text: string; inputRequestId?: number; eof?: boolean }
  | { op: 'key'; key: string; pressed: boolean }
  | { op: 'click'; x: number; y: number; actorId?: string }
  | { op: 'simulation'; action: 'step' | 'start' | 'stop' | 'reset' | 'setSpeed'; speed?: number }
);
export type WorkerCommand = RuntimeCommand | { op: 'compile'; files: ProjectFile[]; library?: ProjectLibrary; resources?: ProjectResource[]; generationId: string };
export interface WorkerReply {
  id: number;
  generationId: string;
  response: RuntimeValue;
  snapshot: RuntimeSnapshot;
}
export type RuntimeEvent = {
  type: 'event';
  generationId: string;
  executionId: number;
  sequence: number;
  kind: 'started' | 'output' | 'snapshot' | 'inputRequested';
  inputRequestId?: number;
  output?: string;
  snapshot: RuntimeSnapshot;
};
