export type FileKind='class'|'functions';
export interface ProjectFile{id:string;fileName:string;kind:FileKind;source:string;revision:number}
export interface TypeRef{classifier:string;arguments:TypeRef[];nullable:boolean;displayName:string;projection?:'in'|'out'|'star'}
export interface CallableMeta{id:string;name:string;declaringType:string;parameters:{name:string;type:TypeRef;hasDefault:boolean}[];returnType:TypeRef;visibility:string;inheritedFrom?:string;typeParameters?:string[]}
export interface CallableMeta { autoGenerated?: boolean; propertyName?: string; companion?: boolean }
export interface ClassMeta{id:string;name:string;qualifiedName?:string;kind:string;constructors:ManifestConstructor[];methods:CallableMeta[];properties:ManifestProperty[];supertypes:TypeRef[];typeParameters:string[]}
export interface ClassMeta { companionMethods?: CallableMeta[] }
export interface ManifestConstructor{ id:string; parameters:{name:string; type:TypeRef; hasDefault:boolean}[] }
export interface ManifestProperty{ id:string; name:string; type:TypeRef; mutable:boolean; visibility:string; getter?:boolean; setter?:boolean; getterId?:string; setterId?:string; generated?:boolean }
export interface ManifestCallable extends CallableMeta{ generated?:boolean; companion?:boolean }
export interface ManifestClass{
    id:string;
    name:string;
    qualifiedName?:string;
    kind:'class'|'abstract'|'interface'|'object'|'enum'|'annotation'|'functions';
    modifiers:string[];
    typeParameters:string[];
    supertypes:TypeRef[];
    constructors:ManifestConstructor[];
    properties:ManifestProperty[];
    methods:ManifestCallable[];
}
export interface SymbolManifest{ version:1; classes:ManifestClass[]; functions:(ManifestCallable & {sourceLine:number})[] }
export interface Diagnostic { fileName?:string; line:number; column:number; severity:'error'|'warning'; message:string }
export interface CompileResult{generationId:string;sourceRevision:number;classes:ClassMeta[];diagnostics:Diagnostic[]}

/** A session has exactly one phase, shared by every UI surface. */
export type Phase = 'uncompiled' | 'compiling' | 'ready' | 'running' | 'waitingForInput' | 'faulted';
export interface InspectedField { name: string; value: string; type?: TypeRef | null }
export interface RuntimeValue {
  kind: 'unit' | 'null' | 'scalar' | 'object' | 'inspect' | 'error';
  display?: string;
  type?: TypeRef;
  objectId?: string;
  className?: string;
  name?: string;
  fields?: InspectedField[];
  phase?: 'request' | 'analysis' | 'runtime' | 'transport';
  fatal?: boolean;
  output?: string;
  stage?: any;
}
export interface RuntimeSnapshot {
  generationId: string;
  revision: number;
  phase: Phase;
  classes: ClassMeta[];
  inspections: Record<string, RuntimeValue>;
  error: string | null;
}
export type RuntimeCommand = { generationId?: string } & (
  | { op: 'eval'; code: string; filename?: string }
  | { op: 'main'; fileName: string }
  | { op: 'create'; className: string; name: string; args: string[]; typeArguments?: string[] }
  | { op: 'invoke'; objectId: string; name: string; args: string[]; typeArguments?: string[] }
  | { op: 'get'; objectId: string; property: string }
  | { op: 'set'; objectId: string; property: string; value: string }
  | { op: 'inspect'; objectId: string }
  | { op: 'bind'; objectId: string; name: string }
  | { op: 'input'; text: string; inputRequestId?: number; eof?: boolean }
  | { op: 'key'; key: string; pressed: boolean }
  | { op: 'click'; x: number; y: number }
);
export type WorkerCommand = RuntimeCommand | { op: 'compile'; files: ProjectFile[]; generationId: string };
export interface WorkerReply {
  id: number;
  generationId: string;
  response: RuntimeValue;
  snapshot: RuntimeSnapshot;
}
export type RuntimeEvent = {
  type: 'event';
  generationId: string;
  executionId: number;
  sequence: number;
  kind: 'started' | 'output' | 'snapshot' | 'inputRequested';
  inputRequestId?: number;
  output?: string;
  snapshot: RuntimeSnapshot;
};
